name: Android Release CI

on:
  create:
    branches:
      - "release/**"
  workflow_dispatch:

jobs:
  versioning:
    uses: ./.github/workflows/versioning.yml

  build:
    needs: versioning
    uses: ./.github/workflows/android-build.yml
    with:
      version: ${{ needs.versioning.outputs.version }}
      build_number: ${{ needs.versioning.outputs.build_number }}
      profile: staging
    secrets: inherit
